# name: GitHub Actions Demo
# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]
# jobs:
#   init:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-varsion: [16.x]
#     steps:
#       - uses: actions/checkout@v3
#       - name: Staring Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: install modules
#         run: npm install
#       - name: build project
#         run: npm run build
#       - name: build storybook
#         run: npm run build:storybook
#       - name: unit test
#         run: npm run test:unit
#       - name: e2e test
#         run: npm run test:e2e
#       - name: lint code
#         run: npm run lint
name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
